// src/components/DarkMode.svelte
<script lang="ts">
  let isDarkMode = localStorage.getItem('darkMode') === 'true'

  $: {
    if (isDarkMode) {
      document.documentElement.classList.add('dark')
    } else {
      document.documentElement.classList.remove('dark')
    }
    localStorage.setItem('darkMode', String(isDarkMode))
  }
</script>

<button on:click={() => (isDarkMode = !isDarkMode)}>
  <span
    class="w-5 h-5 align-sub"
    class:icon-[ph--moon-bold]={isDarkMode}
    class:icon-[ph--sun-bold]={!isDarkMode}
  ></span>
</button>

// src/components/DarkMode.tsx
import { useEffect, useState } from 'react'

export default function DarkMode() {
  const [isDarkMode, setIsDarkMode] = useState(() => {
    const saved = localStorage.getItem('theme')

    return saved === 'dark'
  })

  useEffect(() => {
    const element = document.documentElement

    if (isDarkMode) {
      element.classList.add('dark')
    } else {
      element.classList.remove('dark')
    }

    localStorage.setItem('theme', isDarkMode ? 'dark' : 'light')
  }, [isDarkMode])

  return (
    <button onClick={() => setIsDarkMode(!isDarkMode)}>
      <i className={`w-4 h-4 fa ${isDarkMode ? 'fa-sun' : 'fa-moon'}`} />
    </button>
  )
}
